parameters:
    kunstmaan_node_search.searchconfiguration.node.class: Kunstmaan\NodeSearchBundle\Configuration\NodeSearchConfiguration
    kunstmaan_node_search.indexname: "nodeindex"
    kunstmaan_node_search.indextype: "page"

services:
    kunstmaan_node_search.searchconfiguration.node:
        class: Kunstmaan\NodeSearchBundle\Configuration\NodePagesConfiguration
        arguments: ["%kunstmaan_node_search.indexname%", "%kunstmaan_node_search.indextype%", "@kunstmaan_search.searchprovider.elastica", "%requiredlocales%", "%analyzer_languages%", "@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: kunstmaan_search.searchconfiguration, alias: Node }

    kunstmaan_node_search.search.abstract_elastica_searcher:
        class: Kunstmaan\NodeSearchBundle\Search\AbstractElasticaSearcher
        abstract: true
        calls:
            - [ setProvider, ["@kunstmaan_search.searchprovider.elastica"]]


    kunstmaan_node_search.search.node:
        class: Kunstmaan\NodeSearchBundle\Search\NodeSearcher
        parent: kunstmaan_node_search.search.abstract_elastica_searcher
        calls:
            - [ setIndexName, ["%kunstmaan_node_search.indexname%"]]
            - [ setIndexType, ["%kunstmaan_node_search.indextype%"]]

    kunstmaan_node_search.node_index_update.listener:
        class: Kunstmaan\NodeSearchBundle\EventListener\NodeIndexUpdateEventListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: kunstmaan_node.postPublish, method: onPostPublish }
            - { name: kernel.event_listener, event: kunstmaan_node.postPersist, method: onPostPersist }
            - { name: kernel.event_listener, event: kunstmaan_node.postDelete, method: onPostDelete }
            - { name: kernel.event_listener, event: kunstmaan_node.postUnPublish, method: onPostUnPublish }
